/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.ui;

import com.google.inject.Injector;
import fr.paris10.miage.DslLogs.ui.internal.DslLogsActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslLogsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DslLogsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DslLogsActivator.getInstance().getInjector(DslLogsActivator.FR_PARIS10_MIAGE_DSLLOGS);
	}
	
}
