/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.ui;

import fr.paris10.miage.ui.AbstractDslLogsUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslLogsUiModule extends AbstractDslLogsUiModule {
  public DslLogsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
