/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.dslLogs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.paris10.miage.dslLogs.Action#getPage <em>Page</em>}</li>
 * </ul>
 *
 * @see fr.paris10.miage.dslLogs.DslLogsPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Page</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Page</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Page</em>' attribute.
   * @see #setPage(String)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getAction_Page()
   * @model
   * @generated
   */
  String getPage();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Action#getPage <em>Page</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Page</em>' attribute.
   * @see #getPage()
   * @generated
   */
  void setPage(String value);

} // Action
