/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.dslLogs;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Appel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.paris10.miage.dslLogs.Appel#getParametres <em>Parametres</em>}</li>
 * </ul>
 *
 * @see fr.paris10.miage.dslLogs.DslLogsPackage#getAppel()
 * @model
 * @generated
 */
public interface Appel extends Action
{
  /**
   * Returns the value of the '<em><b>Parametres</b></em>' containment reference list.
   * The list contents are of type {@link fr.paris10.miage.dslLogs.Parametre}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parametres</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametres</em>' containment reference list.
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getAppel_Parametres()
   * @model containment="true"
   * @generated
   */
  EList<Parametre> getParametres();

} // Appel
