/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.dslLogs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.paris10.miage.dslLogs.Date#getAnnee <em>Annee</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Date#getMois <em>Mois</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Date#getJour <em>Jour</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Date#getHeure <em>Heure</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Date#getMinute <em>Minute</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Date#getSeconde <em>Seconde</em>}</li>
 * </ul>
 *
 * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate()
 * @model
 * @generated
 */
public interface Date extends EObject
{
  /**
   * Returns the value of the '<em><b>Annee</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annee</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annee</em>' attribute.
   * @see #setAnnee(int)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate_Annee()
   * @model
   * @generated
   */
  int getAnnee();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Date#getAnnee <em>Annee</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annee</em>' attribute.
   * @see #getAnnee()
   * @generated
   */
  void setAnnee(int value);

  /**
   * Returns the value of the '<em><b>Mois</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mois</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mois</em>' attribute.
   * @see #setMois(int)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate_Mois()
   * @model
   * @generated
   */
  int getMois();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Date#getMois <em>Mois</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mois</em>' attribute.
   * @see #getMois()
   * @generated
   */
  void setMois(int value);

  /**
   * Returns the value of the '<em><b>Jour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Jour</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jour</em>' attribute.
   * @see #setJour(int)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate_Jour()
   * @model
   * @generated
   */
  int getJour();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Date#getJour <em>Jour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jour</em>' attribute.
   * @see #getJour()
   * @generated
   */
  void setJour(int value);

  /**
   * Returns the value of the '<em><b>Heure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Heure</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Heure</em>' attribute.
   * @see #setHeure(int)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate_Heure()
   * @model
   * @generated
   */
  int getHeure();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Date#getHeure <em>Heure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Heure</em>' attribute.
   * @see #getHeure()
   * @generated
   */
  void setHeure(int value);

  /**
   * Returns the value of the '<em><b>Minute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Minute</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minute</em>' attribute.
   * @see #setMinute(int)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate_Minute()
   * @model
   * @generated
   */
  int getMinute();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Date#getMinute <em>Minute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minute</em>' attribute.
   * @see #getMinute()
   * @generated
   */
  void setMinute(int value);

  /**
   * Returns the value of the '<em><b>Seconde</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seconde</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seconde</em>' attribute.
   * @see #setSeconde(int)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDate_Seconde()
   * @model
   * @generated
   */
  int getSeconde();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Date#getSeconde <em>Seconde</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seconde</em>' attribute.
   * @see #getSeconde()
   * @generated
   */
  void setSeconde(int value);

} // Date
