/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.dslLogs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Demande</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.paris10.miage.dslLogs.DslLogsPackage#getDemande()
 * @model
 * @generated
 */
public interface Demande extends Action
{
} // Demande
