/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.dslLogs;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.paris10.miage.dslLogs.DslLogsFactory
 * @model kind="package"
 * @generated
 */
public interface DslLogsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dslLogs";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.paris10.fr/miage/DslLogs";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dslLogs";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslLogsPackage eINSTANCE = fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.ModelImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Logs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__LOGS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.LogImpl <em>Log</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.LogImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getLog()
   * @generated
   */
  int LOG = 1;

  /**
   * The feature id for the '<em><b>Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__DATE = 0;

  /**
   * The feature id for the '<em><b>Utilisateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__UTILISATEUR = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__ACTION = 2;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__PARAMETRE = 3;

  /**
   * The feature id for the '<em><b>Reponse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG__REPONSE = 4;

  /**
   * The number of structural features of the '<em>Log</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.DateImpl <em>Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.DateImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getDate()
   * @generated
   */
  int DATE = 2;

  /**
   * The feature id for the '<em><b>Annee</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__ANNEE = 0;

  /**
   * The feature id for the '<em><b>Mois</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__MOIS = 1;

  /**
   * The feature id for the '<em><b>Jour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__JOUR = 2;

  /**
   * The feature id for the '<em><b>Heure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__HEURE = 3;

  /**
   * The feature id for the '<em><b>Minute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__MINUTE = 4;

  /**
   * The feature id for the '<em><b>Seconde</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__SECONDE = 5;

  /**
   * The number of structural features of the '<em>Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.ParametreImpl <em>Parametre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.ParametreImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getParametre()
   * @generated
   */
  int PARAMETRE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Parametre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.UtilisateurImpl <em>Utilisateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.UtilisateurImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getUtilisateur()
   * @generated
   */
  int UTILISATEUR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR__NAME = 0;

  /**
   * The number of structural features of the '<em>Utilisateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.ActionImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getAction()
   * @generated
   */
  int ACTION = 5;

  /**
   * The feature id for the '<em><b>Page</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PAGE = 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.DemandeImpl <em>Demande</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.DemandeImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getDemande()
   * @generated
   */
  int DEMANDE = 6;

  /**
   * The feature id for the '<em><b>Page</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMANDE__PAGE = ACTION__PAGE;

  /**
   * The number of structural features of the '<em>Demande</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMANDE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.impl.AppelImpl <em>Appel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.impl.AppelImpl
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getAppel()
   * @generated
   */
  int APPEL = 7;

  /**
   * The feature id for the '<em><b>Page</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPEL__PAGE = ACTION__PAGE;

  /**
   * The feature id for the '<em><b>Parametres</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPEL__PARAMETRES = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Appel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPEL_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.paris10.miage.dslLogs.Reponse <em>Reponse</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.paris10.miage.dslLogs.Reponse
   * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getReponse()
   * @generated
   */
  int REPONSE = 8;


  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.paris10.miage.dslLogs.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.paris10.miage.dslLogs.Model#getLogs <em>Logs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Logs</em>'.
   * @see fr.paris10.miage.dslLogs.Model#getLogs()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Logs();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Log <em>Log</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Log</em>'.
   * @see fr.paris10.miage.dslLogs.Log
   * @generated
   */
  EClass getLog();

  /**
   * Returns the meta object for the containment reference '{@link fr.paris10.miage.dslLogs.Log#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Date</em>'.
   * @see fr.paris10.miage.dslLogs.Log#getDate()
   * @see #getLog()
   * @generated
   */
  EReference getLog_Date();

  /**
   * Returns the meta object for the containment reference '{@link fr.paris10.miage.dslLogs.Log#getUtilisateur <em>Utilisateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Utilisateur</em>'.
   * @see fr.paris10.miage.dslLogs.Log#getUtilisateur()
   * @see #getLog()
   * @generated
   */
  EReference getLog_Utilisateur();

  /**
   * Returns the meta object for the containment reference '{@link fr.paris10.miage.dslLogs.Log#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see fr.paris10.miage.dslLogs.Log#getAction()
   * @see #getLog()
   * @generated
   */
  EReference getLog_Action();

  /**
   * Returns the meta object for the containment reference '{@link fr.paris10.miage.dslLogs.Log#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parametre</em>'.
   * @see fr.paris10.miage.dslLogs.Log#getParametre()
   * @see #getLog()
   * @generated
   */
  EReference getLog_Parametre();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Log#getReponse <em>Reponse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reponse</em>'.
   * @see fr.paris10.miage.dslLogs.Log#getReponse()
   * @see #getLog()
   * @generated
   */
  EAttribute getLog_Reponse();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Date <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date</em>'.
   * @see fr.paris10.miage.dslLogs.Date
   * @generated
   */
  EClass getDate();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Date#getAnnee <em>Annee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Annee</em>'.
   * @see fr.paris10.miage.dslLogs.Date#getAnnee()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Annee();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Date#getMois <em>Mois</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mois</em>'.
   * @see fr.paris10.miage.dslLogs.Date#getMois()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Mois();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Date#getJour <em>Jour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Jour</em>'.
   * @see fr.paris10.miage.dslLogs.Date#getJour()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Jour();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Date#getHeure <em>Heure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Heure</em>'.
   * @see fr.paris10.miage.dslLogs.Date#getHeure()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Heure();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Date#getMinute <em>Minute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minute</em>'.
   * @see fr.paris10.miage.dslLogs.Date#getMinute()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Minute();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Date#getSeconde <em>Seconde</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Seconde</em>'.
   * @see fr.paris10.miage.dslLogs.Date#getSeconde()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Seconde();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Parametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parametre</em>'.
   * @see fr.paris10.miage.dslLogs.Parametre
   * @generated
   */
  EClass getParametre();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Parametre#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.paris10.miage.dslLogs.Parametre#getName()
   * @see #getParametre()
   * @generated
   */
  EAttribute getParametre_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Parametre#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.paris10.miage.dslLogs.Parametre#getValue()
   * @see #getParametre()
   * @generated
   */
  EAttribute getParametre_Value();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Utilisateur <em>Utilisateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Utilisateur</em>'.
   * @see fr.paris10.miage.dslLogs.Utilisateur
   * @generated
   */
  EClass getUtilisateur();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Utilisateur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.paris10.miage.dslLogs.Utilisateur#getName()
   * @see #getUtilisateur()
   * @generated
   */
  EAttribute getUtilisateur_Name();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see fr.paris10.miage.dslLogs.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link fr.paris10.miage.dslLogs.Action#getPage <em>Page</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Page</em>'.
   * @see fr.paris10.miage.dslLogs.Action#getPage()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Page();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Demande <em>Demande</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Demande</em>'.
   * @see fr.paris10.miage.dslLogs.Demande
   * @generated
   */
  EClass getDemande();

  /**
   * Returns the meta object for class '{@link fr.paris10.miage.dslLogs.Appel <em>Appel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Appel</em>'.
   * @see fr.paris10.miage.dslLogs.Appel
   * @generated
   */
  EClass getAppel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.paris10.miage.dslLogs.Appel#getParametres <em>Parametres</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres</em>'.
   * @see fr.paris10.miage.dslLogs.Appel#getParametres()
   * @see #getAppel()
   * @generated
   */
  EReference getAppel_Parametres();

  /**
   * Returns the meta object for enum '{@link fr.paris10.miage.dslLogs.Reponse <em>Reponse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Reponse</em>'.
   * @see fr.paris10.miage.dslLogs.Reponse
   * @generated
   */
  EEnum getReponse();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslLogsFactory getDslLogsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.ModelImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Logs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__LOGS = eINSTANCE.getModel_Logs();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.LogImpl <em>Log</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.LogImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getLog()
     * @generated
     */
    EClass LOG = eINSTANCE.getLog();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOG__DATE = eINSTANCE.getLog_Date();

    /**
     * The meta object literal for the '<em><b>Utilisateur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOG__UTILISATEUR = eINSTANCE.getLog_Utilisateur();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOG__ACTION = eINSTANCE.getLog_Action();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOG__PARAMETRE = eINSTANCE.getLog_Parametre();

    /**
     * The meta object literal for the '<em><b>Reponse</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG__REPONSE = eINSTANCE.getLog_Reponse();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.DateImpl <em>Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.DateImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getDate()
     * @generated
     */
    EClass DATE = eINSTANCE.getDate();

    /**
     * The meta object literal for the '<em><b>Annee</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__ANNEE = eINSTANCE.getDate_Annee();

    /**
     * The meta object literal for the '<em><b>Mois</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__MOIS = eINSTANCE.getDate_Mois();

    /**
     * The meta object literal for the '<em><b>Jour</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__JOUR = eINSTANCE.getDate_Jour();

    /**
     * The meta object literal for the '<em><b>Heure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__HEURE = eINSTANCE.getDate_Heure();

    /**
     * The meta object literal for the '<em><b>Minute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__MINUTE = eINSTANCE.getDate_Minute();

    /**
     * The meta object literal for the '<em><b>Seconde</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__SECONDE = eINSTANCE.getDate_Seconde();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.ParametreImpl <em>Parametre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.ParametreImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getParametre()
     * @generated
     */
    EClass PARAMETRE = eINSTANCE.getParametre();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETRE__NAME = eINSTANCE.getParametre_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETRE__VALUE = eINSTANCE.getParametre_Value();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.UtilisateurImpl <em>Utilisateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.UtilisateurImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getUtilisateur()
     * @generated
     */
    EClass UTILISATEUR = eINSTANCE.getUtilisateur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UTILISATEUR__NAME = eINSTANCE.getUtilisateur_Name();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.ActionImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Page</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__PAGE = eINSTANCE.getAction_Page();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.DemandeImpl <em>Demande</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.DemandeImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getDemande()
     * @generated
     */
    EClass DEMANDE = eINSTANCE.getDemande();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.impl.AppelImpl <em>Appel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.impl.AppelImpl
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getAppel()
     * @generated
     */
    EClass APPEL = eINSTANCE.getAppel();

    /**
     * The meta object literal for the '<em><b>Parametres</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPEL__PARAMETRES = eINSTANCE.getAppel_Parametres();

    /**
     * The meta object literal for the '{@link fr.paris10.miage.dslLogs.Reponse <em>Reponse</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.paris10.miage.dslLogs.Reponse
     * @see fr.paris10.miage.dslLogs.impl.DslLogsPackageImpl#getReponse()
     * @generated
     */
    EEnum REPONSE = eINSTANCE.getReponse();

  }

} //DslLogsPackage
