/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.dslLogs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Log</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.paris10.miage.dslLogs.Log#getDate <em>Date</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Log#getUtilisateur <em>Utilisateur</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Log#getAction <em>Action</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Log#getParametre <em>Parametre</em>}</li>
 *   <li>{@link fr.paris10.miage.dslLogs.Log#getReponse <em>Reponse</em>}</li>
 * </ul>
 *
 * @see fr.paris10.miage.dslLogs.DslLogsPackage#getLog()
 * @model
 * @generated
 */
public interface Log extends EObject
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' containment reference.
   * @see #setDate(Date)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getLog_Date()
   * @model containment="true"
   * @generated
   */
  Date getDate();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Log#getDate <em>Date</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' containment reference.
   * @see #getDate()
   * @generated
   */
  void setDate(Date value);

  /**
   * Returns the value of the '<em><b>Utilisateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Utilisateur</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Utilisateur</em>' containment reference.
   * @see #setUtilisateur(Utilisateur)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getLog_Utilisateur()
   * @model containment="true"
   * @generated
   */
  Utilisateur getUtilisateur();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Log#getUtilisateur <em>Utilisateur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Utilisateur</em>' containment reference.
   * @see #getUtilisateur()
   * @generated
   */
  void setUtilisateur(Utilisateur value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getLog_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Log#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

  /**
   * Returns the value of the '<em><b>Parametre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parametre</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametre</em>' containment reference.
   * @see #setParametre(Parametre)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getLog_Parametre()
   * @model containment="true"
   * @generated
   */
  Parametre getParametre();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Log#getParametre <em>Parametre</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parametre</em>' containment reference.
   * @see #getParametre()
   * @generated
   */
  void setParametre(Parametre value);

  /**
   * Returns the value of the '<em><b>Reponse</b></em>' attribute.
   * The literals are from the enumeration {@link fr.paris10.miage.dslLogs.Reponse}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reponse</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reponse</em>' attribute.
   * @see fr.paris10.miage.dslLogs.Reponse
   * @see #setReponse(Reponse)
   * @see fr.paris10.miage.dslLogs.DslLogsPackage#getLog_Reponse()
   * @model
   * @generated
   */
  Reponse getReponse();

  /**
   * Sets the value of the '{@link fr.paris10.miage.dslLogs.Log#getReponse <em>Reponse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reponse</em>' attribute.
   * @see fr.paris10.miage.dslLogs.Reponse
   * @see #getReponse()
   * @generated
   */
  void setReponse(Reponse value);

} // Log
