/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.validation;

import fr.paris10.miage.dslLogs.Appel;
import fr.paris10.miage.dslLogs.Demande;
import fr.paris10.miage.dslLogs.DslLogsPackage;
import fr.paris10.miage.dslLogs.Model;
import fr.paris10.miage.validation.AbstractDslLogsValidator;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslLogsValidator extends AbstractDslLogsValidator {
  @Check(CheckType.NORMAL)
  public Object checkDateOrdreChronologique(final Model model) {
    return null;
  }
  
  public final static String ERROR_EXT_JSP = "invalidExtension";
  
  @Check(CheckType.FAST)
  public void checkAppelsJspPage(final Appel appel) {
    String _page = appel.getPage();
    boolean _endsWith = _page.endsWith(".jsp");
    boolean _not = (!_endsWith);
    if (_not) {
      this.warning("Extension invalide !", DslLogsPackage.Literals.APPEL__PARAMETRES, DslLogsValidator.ERROR_EXT_JSP);
    }
  }
  
  @Check(CheckType.FAST)
  public void checkDemandesHtmlPage(final Demande demande) {
    String _page = demande.getPage();
    boolean _endsWith = _page.endsWith(".html");
    boolean _not = (!_endsWith);
    if (_not) {
      this.warning("Extension invalide !", DslLogsPackage.Literals.ACTION__PAGE, DslLogsValidator.ERROR_EXT_JSP);
    }
  }
}
