/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.ui.tests;

import com.google.inject.Injector;
import fr.paris10.miage.DslLogs.ui.internal.DslLogsActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DslLogsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslLogsActivator.getInstance().getInjector("fr.paris10.miage.DslLogs");
	}

}
