/**
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage;

import fr.paris10.miage.AbstractDslLogsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslLogsRuntimeModule extends AbstractDslLogsRuntimeModule {
}
