/*
 * generated by Xtext 2.10.0
 */
package fr.paris10.miage.parser.antlr;

import com.google.inject.Inject;
import fr.paris10.miage.parser.antlr.internal.InternalDslLogsParser;
import fr.paris10.miage.services.DslLogsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DslLogsParser extends AbstractAntlrParser {

	@Inject
	private DslLogsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDslLogsParser createParser(XtextTokenStream stream) {
		return new InternalDslLogsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DslLogsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslLogsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
